#!/bin/sh -e
#
# Shell script for GODI installation.
#
# Usage: godi-setup http://download.camlcity.org/download/godi-rocketboost-20080630.tar.gz
#

H=/opt/godi
G=$1

wget -O godi.tar.gz $G
tar -zxvf godi.tar.gz
cd godi-rocketboost*
./bootstrap --prefix $H
mkdir -p /etc/profile.d
echo "export PATH=$H/bin:$H/sbin:\$PATH" > /etc/profile.d/godi.sh
echo "export MANPATH=$H/man:\$MANPATH"  >> /etc/profile.d/godi.sh
chmod +x /etc/profile.d/godi.sh
source /etc/profile
echo "GODI_BASEPKG_PCRE=yes" >> $H/etc/godi.conf
./bootstrap_stage2


