#!/bin/sh

GODI_HOME=/opt/godi
CONSOLE="$GODI_HOME/sbin/godi_console"

gp_install () {
    echo "installing $1"
    $CONSOLE perform -build $1
}

gp_install "godi-getopt"
gp_install "godi-pcre"
gp_install "godi-ocamlnet"
gp_install "godi-ocamldap"
gp_install "godi-ocs"
gp_install "godi-crypt"
gp_install "godi-ocamlldap"
gp_install "godi-ulex"
gp_install "godi-pxp"
gp_install "godi-syslog"
gp_install "godi-zip"
gp_install "godi-postgresql"
